"""Test file generator for PySpark transformations."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..inference.schema import SchemaAnalysis, SchemaComparison

from .paths import TestPaths

logger = logging.getLogger(__name__)


class TestWriter:
    """Generates pytest test files for DataFrame transformations.

    Creates test files with:
    - Schema stability tests
    - Snapshot comparison tests
    - Null/edge case handling tests
    - Soft plan regression tests
    """

    def generate(
        self,
        function_name: str,
        _input_analysis: SchemaAnalysis,
        output_analysis: SchemaAnalysis,
        schema_comparison: SchemaComparison,
        paths: TestPaths,
    ) -> str:
        """Generate test file content.

        Args:
            function_name: Name of the function being tested
            _input_analysis: Analysis of input schema (unused, reserved for future)
            output_analysis: Analysis of output schema
            schema_comparison: Comparison between input/output schemas
            paths: TestPaths for resource locations

        Returns:
            Complete test file content as string
        """
        sections = [
            self._generate_header(function_name),
            self._generate_imports(),
            self._generate_constants(function_name, paths),
            self._generate_fixtures(function_name),
            self._generate_helper_functions(),
            self._generate_schema_tests(output_analysis, schema_comparison),
            self._generate_snapshot_tests(function_name),
            self._generate_null_handling_tests(function_name, output_analysis),
            self._generate_plan_tests(function_name),
        ]

        return "\n\n".join(sections)

    def write(self, content: str, path: Path) -> None:
        """Write test content to file.

        Args:
            content: Test file content
            path: Target file path
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info(f"Generated test file: {path}")

    def _generate_header(self, function_name: str) -> str:
        """Generate file header with docstring."""
        return dedent(f'''\
            """
            Auto-generated tests for `{function_name}`.

            Generated by spark-testgen. These tests verify:
            - Schema stability
            - Output snapshot matching
            - Null value handling
            - Execution plan stability (soft check)

            To use these tests:
            1. Import your transformation function
            2. Uncomment the function call lines
            3. Run: pytest {Path("tests") / f"test_{function_name}.py"}

            After verifying tests pass, you can customize them as needed.
            """''')

    def _generate_imports(self) -> str:
        """Generate import statements."""
        return dedent("""\
            from pathlib import Path

            import pytest
            from pyspark.sql import DataFrame, SparkSession
            from pyspark.sql.types import (
                ArrayType,
                BooleanType,
                DateType,
                DoubleType,
                FloatType,
                IntegerType,
                LongType,
                MapType,
                StringType,
                StructField,
                StructType,
                TimestampType,
            )""")

    def _generate_constants(self, function_name: str, paths: TestPaths) -> str:
        """Generate constants section."""
        relative_path = paths.relative_resource_path()
        return dedent(f'''\
            # =============================================================================
            # Configuration
            # =============================================================================

            # Path to test resources (relative to this test file)
            RESOURCE_DIR = Path(__file__).parent / "{relative_path}"

            # TODO: Import your transformation function here
            # from your_module import {function_name}''')

    def _generate_fixtures(self, function_name: str) -> str:
        """Generate pytest fixtures."""
        return dedent(f'''\
            # =============================================================================
            # Fixtures
            # =============================================================================


            @pytest.fixture(scope="module")
            def spark() -> SparkSession:
                """Create a SparkSession for testing."""
                return (
                    SparkSession.builder.master("local[1]")
                    .appName("test_{function_name}")
                    .config("spark.sql.shuffle.partitions", "1")
                    .config("spark.default.parallelism", "1")
                    .config("spark.ui.enabled", "false")
                    .getOrCreate()
                )


            @pytest.fixture
            def input_df(spark: SparkSession) -> DataFrame:
                """Load the input DataFrame from snapshot."""
                return spark.read.parquet(str(RESOURCE_DIR / "input.parquet"))


            @pytest.fixture
            def expected_output_df(spark: SparkSession) -> DataFrame:
                """Load the expected output DataFrame from snapshot."""
                return spark.read.parquet(str(RESOURCE_DIR / "output.parquet"))


            @pytest.fixture
            def edge_cases_df(spark: SparkSession) -> DataFrame | None:
                """Load edge cases DataFrame if available."""
                edge_cases_path = RESOURCE_DIR / "edge_cases_input.parquet"
                if edge_cases_path.exists():
                    return spark.read.parquet(str(edge_cases_path))
                return None''')

    def _generate_helper_functions(self) -> str:
        """Generate helper functions for test assertions."""
        return dedent('''\
            # =============================================================================
            # Helper Functions
            # =============================================================================


            def assert_schemas_equal(
                actual: StructType,
                expected: StructType,
                check_nullable: bool = True,
            ) -> None:
                """Assert two schemas are equal.

                Args:
                    actual: Actual schema
                    expected: Expected schema
                    check_nullable: Whether to check nullability
                """
                assert len(actual.fields) == len(expected.fields), (
                    f"Field count mismatch: {len(actual.fields)} vs {len(expected.fields)}"
                )

                for actual_field, expected_field in zip(actual.fields, expected.fields):
                    assert actual_field.name == expected_field.name, (
                        f"Field name mismatch: {actual_field.name} vs {expected_field.name}"
                    )
                    assert str(actual_field.dataType) == str(expected_field.dataType), (
                        f"Field type mismatch for {actual_field.name}: "
                        f"{actual_field.dataType} vs {expected_field.dataType}"
                    )
                    if check_nullable:
                        assert actual_field.nullable == expected_field.nullable, (
                            f"Nullability mismatch for {actual_field.name}: "
                            f"{actual_field.nullable} vs {expected_field.nullable}"
                        )


            def assert_dataframes_equal(
                actual: DataFrame,
                expected: DataFrame,
                check_order: bool = False,
            ) -> None:
                """Assert two DataFrames have equal content.

                Args:
                    actual: Actual DataFrame
                    expected: Expected DataFrame
                    check_order: Whether row order matters
                """
                # Check schemas match
                assert_schemas_equal(actual.schema, expected.schema)

                # Get data
                if check_order:
                    actual_rows = actual.collect()
                    expected_rows = expected.collect()
                else:
                    # Sort by all columns for comparison
                    sort_cols = [f.name for f in actual.schema.fields]
                    actual_rows = actual.orderBy(*sort_cols).collect()
                    expected_rows = expected.orderBy(*sort_cols).collect()

                assert len(actual_rows) == len(expected_rows), (
                    f"Row count mismatch: {len(actual_rows)} vs {len(expected_rows)}"
                )

                for i, (actual_row, expected_row) in enumerate(zip(actual_rows, expected_rows)):
                    assert actual_row == expected_row, (
                        f"Row {i} mismatch:\\n  Actual: {actual_row}\\n  Expected: {expected_row}"
                    )''')

    def _generate_schema_tests(
        self,
        output_analysis: SchemaAnalysis,
        schema_comparison: SchemaComparison,
    ) -> str:
        """Generate schema stability tests."""
        # Generate expected field list
        fields_code = []
        for field_info in output_analysis.fields:
            fields_code.append(
                f'        ("{field_info.name}", "{field_info.data_type}", {field_info.nullable}),'
            )
        fields_str = "\n".join(fields_code)

        # Generate added/removed field assertions
        added_check = ""
        if schema_comparison.added_fields:
            added_list = ", ".join(f'"{f}"' for f in schema_comparison.added_fields)
            added_check = f'''

                    # Verify expected new columns are present
                    expected_added = [{added_list}]
                    for col in expected_added:
                        assert col in output_cols, f"Expected added column '{{col}}' not found"'''

        return dedent(f'''\
            # =============================================================================
            # Schema Tests
            # =============================================================================


            class TestSchema:
                """Tests for schema stability."""

                def test_output_has_expected_fields(
                    self, spark: SparkSession, input_df: DataFrame
                ) -> None:
                    """Verify output schema has all expected fields."""
                    # TODO: Uncomment and call your transformation
                    # result = {schema_comparison.common_fields[0] if schema_comparison.common_fields else "your_function"}(input_df)

                    # For now, use expected output
                    result = spark.read.parquet(str(RESOURCE_DIR / "output.parquet"))

                    expected_fields = [
            {fields_str}
                    ]

                    output_cols = [f.name for f in result.schema.fields]

                    for name, dtype, nullable in expected_fields:
                        assert name in output_cols, f"Missing field: {{name}}"{added_check}

                def test_schema_matches_snapshot(
                    self, spark: SparkSession, expected_output_df: DataFrame, input_df: DataFrame
                ) -> None:
                    """Verify output schema matches the captured snapshot schema."""
                    # TODO: Uncomment and call your transformation
                    # result = your_function(input_df)
                    result = expected_output_df  # Using snapshot for now

                    assert_schemas_equal(result.schema, expected_output_df.schema)''')

    def _generate_snapshot_tests(self, function_name: str) -> str:
        """Generate snapshot comparison tests."""
        return dedent(f'''\
            # =============================================================================
            # Snapshot Tests
            # =============================================================================


            class TestSnapshot:
                """Tests for output data matching captured snapshot."""

                def test_output_matches_snapshot(
                    self,
                    spark: SparkSession,
                    input_df: DataFrame,
                    expected_output_df: DataFrame,
                ) -> None:
                    """Verify output data matches the captured snapshot."""
                    # TODO: Uncomment and call your transformation
                    # result = {function_name}(input_df)
                    result = expected_output_df  # Using snapshot for now

                    assert_dataframes_equal(result, expected_output_df)

                def test_row_count_preserved(
                    self,
                    spark: SparkSession,
                    input_df: DataFrame,
                    expected_output_df: DataFrame,
                ) -> None:
                    """Verify row count relationship between input and output."""
                    # TODO: Uncomment and call your transformation
                    # result = {function_name}(input_df)
                    result = expected_output_df  # Using snapshot for now

                    input_count = input_df.count()
                    output_count = result.count()

                    # Adjust assertion based on your transformation's behavior
                    # For filter operations: assert output_count <= input_count
                    # For explode operations: assert output_count >= input_count
                    # For 1:1 transformations:
                    assert output_count == expected_output_df.count()''')

    def _generate_null_handling_tests(
        self, function_name: str, output_analysis: SchemaAnalysis
    ) -> str:
        """Generate null handling tests."""
        nullable_list = ", ".join(f'"{f}"' for f in output_analysis.nullable_fields[:5])

        return dedent(f'''\
            # =============================================================================
            # Null Handling Tests
            # =============================================================================


            class TestNullHandling:
                """Tests for null value handling."""

                def test_handles_edge_cases(
                    self,
                    spark: SparkSession,
                    edge_cases_df: DataFrame | None,
                ) -> None:
                    """Verify function handles edge cases without errors."""
                    if edge_cases_df is None:
                        pytest.skip("No edge cases file available")

                    # TODO: Uncomment and call your transformation
                    # result = {function_name}(edge_cases_df)

                    # For now, just verify edge cases load correctly
                    assert edge_cases_df.count() > 0, "Edge cases should have rows"

                def test_null_values_handled(
                    self,
                    spark: SparkSession,
                    input_df: DataFrame,
                ) -> None:
                    """Verify null values are handled appropriately."""
                    # Create input with nulls in nullable columns
                    nullable_columns = [{nullable_list}]

                    if not nullable_columns:
                        pytest.skip("No nullable columns to test")

                    # TODO: Uncomment and call your transformation
                    # result = {function_name}(input_df)

                    # Verify no unexpected exceptions (implicit test)
                    assert True  # Placeholder - customize based on expected behavior''')

    def _generate_plan_tests(self, function_name: str) -> str:
        """Generate execution plan regression tests."""
        return dedent(f'''\
            # =============================================================================
            # Plan Regression Tests (Soft)
            # =============================================================================


            class TestPlanRegression:
                """Soft tests for execution plan stability.

                These tests are informational and may fail due to Spark version
                differences or optimizer changes. They help catch unintended
                changes to query structure.
                """

                def test_logical_plan_stable(
                    self,
                    spark: SparkSession,
                    input_df: DataFrame,
                ) -> None:
                    """Soft check that logical plan structure is similar."""
                    plan_file = RESOURCE_DIR / "plan_logical.txt"
                    if not plan_file.exists():
                        pytest.skip("No logical plan snapshot available")

                    expected_plan = plan_file.read_text()

                    # TODO: Uncomment and call your transformation
                    # result = {function_name}(input_df)
                    # actual_plan = result._jdf.queryExecution().logical().toString()

                    # For now, just verify plan file is readable
                    assert len(expected_plan) > 0, "Logical plan should not be empty"

                    # Soft comparison - uncomment when function is connected
                    # This is a soft check; plan differences may be acceptable
                    # assert _plans_similar(actual_plan, expected_plan), (
                    #     "Logical plan has changed significantly"
                    # )

                def test_physical_plan_exists(
                    self,
                    spark: SparkSession,
                ) -> None:
                    """Verify physical plan snapshot exists."""
                    plan_file = RESOURCE_DIR / "plan_physical.txt"
                    assert plan_file.exists(), "Physical plan snapshot should exist"

                    content = plan_file.read_text()
                    assert len(content) > 0, "Physical plan should not be empty"''')
